### PR TITLE
Dev#05032018

### PR DESCRIPTION
**Pull request by jeong760**
Dear Bonesoul,

I've fixed and updated following so after review please applied this PR to your repository.

- fixed a display correct pool hash rate 
   Actually I've refers to this on [#763](https://github.com/bonesoul/CoiniumServ/pull/763)
   It has been merged on Jan of 2017 but current repo does not have this info 
   so CoiniumServ does not displayed a correct pool hash rate
- added a Globaltoken.json and its icon on /src/web/default/Contents/img/coins/icon
- added an advanced-exmaple.json
- added a config-example.json
- added a default-example.json
- added a bitcoin-exmaple.json
- added a globaltoken-example.json
- removed a contents on default.json
- remoced a contents on pool.json
- update a following Nuget packages for CoiniumServ
 **src/CoiniumServ/packages.config**
   "Microsoft.AspNet.Razor" version="3.2.4"
   "MySql.Data" version="6.9.11"
   "Newtonsoft.Json" version="11.0.1"
   "StackExchange.Redis" version="1.2.6"

  **src/Tests/packages.config**
    "Castle.Core" version="4.2.1"
    "Newtonsoft.Json" version="11.0.1"
    "NSubstitute" version="3.1.0"
    "System.Threading.Tasks.Extensions" version="4.4.0"

### CODE REVIEW

**Comment by jeong760** [comment]
@bonesoul, could you review and merged this PR if there are no any issues.

**Comment by bonesoul** [comment]
as far as i remember there is an ongoing bug with new mysql.data releases, we better don't upgrade without proper testing of database subsystem.

**Comment by jeong760** [comment]
@bonesoul, ok, then please merge remaining things.

**Comment by jeong760** [comment]
@bonesoul, I will closed this PR and will open another soon. Because after upgrade of coin daemons(Bitcoin and Globaltoken) it does not support a “Getinfo” command anymore.

**Pull request closed without merging**
