### PR TITLE
xunit 2 upgrade

### PR DESCRIPTION
**Pull request by bonesoul**

### CODE REVIEW

**Comment by bonesoul** [comment]
for appveyor failing; the issue is - http://help.appveyor.com/discussions/problems/5731-outdated-nuget-version

we should get rid of it.

**Comment by bonesoul** [comment]
two tests failing now;

```
Discovering tests...OK
%xunit20%\xunit.console.x86 "C:\projects\coiniumserv\src\Tests\bin\Debug\CoiniumServ.Tests.dll" -appveyor
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: CoiniumServ.Tests
  Discovered:  CoiniumServ.Tests
  Starting:    CoiniumServ.Tests
    CoiniumServ.Tests.Banning.BanConfigTests.InvalidConfig_ShouldReturnDefaults [FAIL]
      Should.Core.Exceptions.EqualException : Assert.Equal() Failure
      Expected: 600
      Actual:   0
      Stack Trace:
        src\Tests\Banning\BanConfigTests.cs(75,0): at CoiniumServ.Tests.Banning.BanConfigTests.InvalidConfig_ShouldReturnDefaults()
    CoiniumServ.Tests.Banning.BanConfigTests.ValidConfig_ShouldSuccess [FAIL]
      Should.Core.Exceptions.EqualException : Assert.Equal() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Tests\Banning\BanConfigTests.cs(55,0): at CoiniumServ.Tests.Banning.BanConfigTests.ValidConfig_ShouldSuccess()
  Finished:    CoiniumServ.Tests
=== TEST EXECUTION SUMMARY ===
   CoiniumServ.Tests  Total: 48, Errors: 0, Failed: 2, Skipped: 0, Time: 1.190s
Command exited with code 2
```

**Comment by bonesoul** [comment]
from travis documentation - https://docs.travis-ci.com/user/languages/csharp/

Note: There’s a bug in Mono that makes xunit 2.0 hang after test execution, we recommended you stick with 1.9.2 until it is fixed.

https://github.com/mono/mono/pull/1654

**Comment by Marekkon5** [comment]
Hello, I get this error with 1.9.2

**Comment by jeong760** [comment]
@Marekkon5, which beranch did you download?

**Pull request closed without merging**
