### PR TITLE
Fixed a network hash rate issue on bitcoin and add a Globaltoken

### PR DESCRIPTION
**Pull request by jeong760**
Dear Bonesoul,

I've solved a network hash rate issue on Bitcoin core version 15.1 and added a globaltoken with new coin config and its icon for the web. 

Please review and applied this to your Develop repository. 

- Added a new coin, name of Globaltoken
- Fixed a network hash rate issue on Bitcoin core.

Regards,
John Ahn

### CODE REVIEW

**Comment by bonesoul** [comment]
thanks for your work, i have to check the altcoins too see if this change doesn't brake them (which i suspect so).

**Comment by Maleksh** [comment]
hi, 
how can I compile it to work on windows

**Comment by jeong760** [comment]
@bonesoul, Yes please check Altcoins but I have a Globaltoken (GLT), which uses a sha256 algorithm have no effect yet. 

@Maleksh if you want a merge for this PR in your source code, then please see a #933 Bitcoin Getworkhashps overflow on issue tab. There I've described where you need to change.

**Comment by jeong760** [comment]
Dears,

Please installation a Visual Studio community and download a CoiniumServ source code then make a compile.

Regards,
John Ahn-----Original Message-----

**Comment by bonesoul** [comment]
Can anyone confirm this patch is working with altcoins like litecoin and so?

**Comment by jeong760** [comment]
Globaltoken has no issue to get its mininginfo after chnaged.

**Comment by jeong760** [comment]
@bonesoul when do you merged this PR?

**Pull request merged**
